Repository dothidden/writeups, pull requests merged in 2023-06, with the labels that each got.

#6 refactor(stranger-case): Update ranking
  content/stranger_case/_index.md
Labels: refactor :hammer:

#35 feat: add option to display author for writeups
  layouts/_default/single.html
Labels: feat :star:

#17 4 bug tags redirection to not found
  assets/css/main.css
  content/dantectf_2023/_index.md
  content/heroctf_v5/_index.md
  content/n00bzctf_2023/_index.md
  content/pwnme_qualifications_2023/_index.md
  content/stranger_case/_index.md
  content/umdctf_2023/_index.md
  content/unbreakable_2023/_index.md
  layouts/_default/list.html
  layouts/_default/term.html
Labels: bug :bug:

#22 8 feat add about page
  assets/css/dark.css
  assets/css/main.css
  config.yaml
  content/about/index.md
  layouts/_default/list.html
  layouts/_default/single.html
  layouts/about/single.html
Labels: feat :star:

#30 24 refactor add n00bz writeup
  content/n00bzctf_2023/asm.md
  content/n00bzctf_2023/bf.md
  content/n00bzctf_2023/mypin.md
  content/n00bzctf_2023/strings.md
  content/n00bzctf_2023/vm.md
  content/n00bzctf_2023/zzz.md
Labels: refactor :hammer:

#37 REFACTOR: Add authors to writeup we already made
  content/dantectf_2023/_index.md
  content/dantectf_2023/almost_perfect_remote_signing.md
  content/dantectf_2023/demonic_navigation_skills.md
  content/dantectf_2023/dirty_checkerboard.md
  content/dantectf_2023/imago.md
  content/dantectf_2023/piedpic.md
  content/dantectf_2023/routesMarkTheSpot.md
  content/dantectf_2023/soulcode.md
  content/dantectf_2023/strangeBytes.md
  content/dantectf_2023/whoCanHazFlag.md
  content/n00bzctf_2023/_index.md
  content/n00bzctf_2023/damn.md
  content/n00bzctf_2023/johnDoesStrikesAgain.md
  content/n00bzctf_2023/lost.md
  content/n00bzctf_2023/maas.md
  content/n00bzctf_2023/missionMoon.md
  content/n00bzctf_2023/pwn1.md
  content/n00bzctf_2023/pwn2.md
  content/n00bzctf_2023/pwn3.md
  content/n00bzctf_2023/rsa.md
  content/n00bzctf_2023/theOnlineOdyssey.md
  content/n00bzctf_2023/tryHackMe.md
  content/stranger_case/_index.md
  content/stranger_case/report.md
  content/stranger_case/sockpuppet.md
  content/unbreakable_2023/_index.md
  content/unbreakable_2023/do_you_hunt_2.md
  content/unbreakable_2023/hidden_art.md
  content/unbreakable_2023/hidden_wave.md
  content/unbreakable_2023/ipv6_evil.md
  content/unbreakable_2023/network_detective.md
Labels: refactor :hammer:

#40 feat(contact): add contact email in about page
  content/about/index.md
Labels: refactor :hammer:
